[package]
name = "bitnet-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rust bindings for bitnet.cpp"


[dependencies]
cxx = "1.0"       # for binding to C++

[build-dependencies]
cxx-build = "1.0" # for building the bindings
glob = "0.3"
